blueprint:
  name: Turn Light, Switch, Entity or Scene On & Off with Trigger Conditions
  description: >
    # ⚙️ Turn Light, Switch, Entity or Scene On & Off with Trigger Conditions
    
    **Version: 2.0**
    
    
    Trigger-Ready Control - Customize On & Off for Light, Switch, Scene, or Any Entity 🚦


    **If you like my blueprints, and would like to show your support or just say thank you?** [Click Here](https://www.paypal.com/donate/?hosted_button_id=WAZS3QSDTPGA8) 🙂

    
    <details>
    <summary><b>The Automation Process:</b> - Click here to expand</summary>

    
      - **Trigger Options:**
        - **Entity State Option:**
          - When an entity changes its state from OFF to ON, the automation will turn specified entities ON.
          - When an entity changes its state from ON to OFF, the automation will turn specified entities OFF.

        - **Sun Option:**
          - When the sun's elevation falls below a set value, the automation will turn specified entities ON.
          - When the sun's elevation rises above a set value, the automation will turn specified entities OFF. 

        - **Ambient Light Sensing Option:**
          - When the ambient Light Sensor falls below a set LUX value, the automation will turn specified entities ON.
          - When the ambient Light Sensor rises above a set LUX value, the automation will turn specified entities OFF. 

        - **Time-Based Option:**
          - Specify precise start and end times to define when the automation should turn specified entities ON and OFF.

      - **Scene Integration:**
        - Scenes offer additional customization for your spaces.

      - **Manual Override:**
        - Use "Bypass Options" for manually bypassing the trigger options. This provides manual control and additional customization.

      - **Weekdays Global Condition Option:**
        - Specify the weekday selections to define when the automation can run.

      - **Custom Conditions:**
          - Enter any custom conditions to further customize the automation process.
    </details>


    Need help? See our FAQ: [Click Here](https://community.home-assistant.io/t/turn-light-switch-or-scene-on-off-with-trigger-conditions/527354/2?u=blacky)

    Let us know what you think of this blueprint and for community support including updates: [Click Here](https://community.home-assistant.io/t/turn-light-switch-or-scene-on-off-with-trigger-conditions/527354?u=blacky)

    
    Required = *
  domain: automation
  input:
    entity_switch:
      name: Lights - Switches - Entities - Scenes *
      description: The lights that get turned ON and OFF with a binary sensor, the sun's elevation, an ambient light value or time.
        You can also add switches and scenes. If adding a scene please read "Scenes To Turn OFF" below.


        **NOTE** - You can only use entities. Areas, devices and labels are not supported.
      selector:
        target:
    end_scenes:
      name: Scenes To Turn OFF
      description: If you have selected a scene to be turned ON above in "Lights - Switches - Entities - Scenes" and you would like it to be turned OFF,
        then you must create another identical scene with everything OFF and select it here.
      default: []
      selector:
        entity:
          multiple: true
          filter:
            domain:
              - scene
    include_bypass:
      name: Use The Bypass Option (Optional)
      description: This will bypass the automation preventing it from running.
      default: bypass_disabled
      selector:
        select:
          options:
            - label: Enable the Bypass option
              value: "bypass_enabled"
            - label: Disable the Bypass option
              value: "bypass_disabled"
    motion_bypass:
      name: By-pass
      description: Select the switch that will bypass the trigger options. 
        The entity cannot be included in the "Lights - Switches - Entities - Scenes" selection.
      default: []
      selector:
        entity:
    include_entity_input:
      name: Use The Entity State Option (Optional)
      description: This is used for adding a trigger when an entity changes it's state from ON to OFF or from OFF to ON. It will not work correctly with a motion sensor.
        
        
        If you would like to use a motion sensor then please consider this blueprint [Click Here](https://community.home-assistant.io/t/481048)
      default: entity_disabled
      selector:
        select:
          options:
            - label: Enable the entity state option entity_disabled
              value: "entity_enabled"
            - label: Disable the entity state option 
              value: "entity_disabled"
   
